### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#367]
* Zeplin - https://zpl.io/aREYDlN
* ignore button groups in design. It's a separate issue #368
* If something seems iffy - consult references or let's discuss. No guessing. This component is too low level for that.

- [x] Hover and focus effects should be the same
- [x] large/small props should play nicely with button sizes #366.
- [x] For icons we should implement them the way they work in vuetify, aka handled with styles and provided via default slot. Do a placeholder, then wait for #366 to add appropriate styles.
- [x] Perform component checks (#378)

### Tag
- [x] tag should be `button` by default
- [x] tag should be `a` if we use `href` prop
- [x] tag should be` router-link` if any of router-link props are used (see https://router.vuejs.org/api/#router-link-props)
- [x] you can still set `tag` as a prop and that takes highest priority
- [x] try to do router support in one place so it's easier to mantain

### Props
- [x] tag: String (see above)
- [x] outline: Boolean (test for all colors/sizes)
- [x] color: String, default: 'vuestic-green'. We first compare with a set of theme colors (primary, secondary, info, error, warning), then we fallback to exact color as provided. So that user can use hash or rgb color. Ideally we also want gradient to stick to selected color, regardless of format.
- [x] small: Boolean
- [x] large: Boolean
- [x] type: String - [button type](https://www.w3schools.com/tags/att_button_type.asp).
- [x] disabled: Boolean
- [x] should allow other native attributes (for target, name etc).
- [x] flat: Boolean. Text button in design. Padding should stay the same.

### References
* Vuetify: https://vuetifyjs.com/en/components/buttons
* Quasar: https://quasar-framework.org/components/button.html

### Testing
- [x] Ideally we want some regression tests running on that (to keep router support with new versions etc) but that's low priority.

![](https://user-images.githubusercontent.com/5394573/48206154-c4169980-e37e-11e8-8ffc-98c234851b7f.png)
![](https://i.imgur.com/uST2eNh.png)

**Comment by asvae** [comment]
And why do you reopen pull requests?
