### ISSUE TITLE
Vuestic 2.0 components

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#370]
Design document https://xx13.github.io/vuestic_redesign/
Mock ups (Zeplin): https://app.zeplin.io/project/5bcd9657767a220982a4ab61

### Components
- [x] Button #367 
- [x] Button group #368
- [x] Button toggle #457 [wip]
- [x] Icon #366 
- [x] Card #375
- [x] Input #329
- [x] Datepicker #507  
- [x] Select #495 
- [x] Table #480 
- [x] Tabs #379
- [x] Modal #454 
- [x] Notification #406
- [x] Pagination #376
- [x] Progress bar #446
- [x] Ratings #459 
- [x] Slider #471
- [x] Timeline component restyle #482 
- [x] Tree view restyle #525 
- [x] File upload restyle #526 
- [x] Date picker restyle #483 
- [ ] Toast restyle
- [x] Tooltip restyle #484 
- [x] Dropdown #478 
- [x] Popover restyle
- [ ] ~Wizard remake~
- [x] Tags restyle #496 
- [x] List #545 (2.1)

### Other
- [x] Typography #371
- [x] Color #373
- [x] Colors refactor #365
- [x] Colors demo #415
- [x] Link class #372
- [x] Content class #374

### To be implemented in presentation
- [ ] Button select https://i.imgur.com/e5HynWO.png https://zpl.io/V4v16Lp
- [ ] ~Logo https://zpl.io/awmYpvn~
