### ISSUE TITLE
Milestone 2.0 Bugs

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-admin#474]
- [x] Corrupted Tooltip (reproduced on develop branch)
- [x] Corrupted Header dropdowns (reproduced on develop branch)
- [x] Vuestic profile card view looks weird (see Dashboard and Extra pages tabs)
- [x] No border bottom line on Tabs widget (Extra page)

**Comment by AlexanderBoriskin** [comment]
Tooltips and Header dropdown were updated and restyled, first two points are not relevant
Issue can be closed
