### ISSUE TITLE
Handle epic-spinners issues

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#493]
The problem:
Problem at hand is this critical [issue](https://github.com/epicmaxco/epic-spinners/issues/24) that spams console on vuestic-admin dashboard.

The solution (AOE): 
- [ ] check [all issues](https://github.com/epicmaxco/epic-spinners/issues) in epic-spinners and evaluate severity (bug|question etc).
- [ ] create a ticket in `vuestic-admin` with list of issues we want to fix. These will be included in next sprint.
- [ ] check [all PRs](https://github.com/epicmaxco/epic-spinners/pulls) in epic-spinner and act on each one.
