### ISSUE TITLE
Add build version to meta

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#676]
The idea is to mark build with commit + branch + timestamp. So we can be sure we're having the correct version on remote server.

- [x] Should be off by default (you can check VUE_APP_INCLUDE_DEMOS flag as example).
- [ ] Should go in meta.
- [x] Feature should be documented (in vuestic-admin, for vuestic-ui it's dev only).
 **Not applyed to vuestic-ui.**

- [x] After you're done, please create an issue in vuestic-ui to implement this. Optionally, you can continue with implementation by yourself.

Some code for reference (please don't just copy):

```js
  // vue.config.js
  chainWebpack: config => {
    config.plugin('define').tap(definitions => {
      definitions[0] = Object.assign(definitions[0], {
        'VERSION_INFO': JSON.stringify(generateFooter())
      })
      return definitions
    })
  },
```

```
// generate-footer.js
function generateFooter () {
  const commit = getLastCommitHash()
  const timestamp = new Date().toUTCString()
  return `Copyright 2011-2019 Vuestic, Build: ${commit}, ${timestamp}`
}

function getLastCommitHash () {
  const hash = require('child_process').execSync('git rev-parse HEAD')
  return hash.slice(0, 6)
}

module.exports = {
  generateFooter
}
```

**Comment by asvae** [comment]
How do I check this is done?

**Comment by Kreezag** [comment]
Sorry, this PR
https://github.com/epicmaxco/vuestic-admin/pull/686
