### ISSUE TITLE
Tracking issue for the problems found during a rewrite

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-admin#875]
- Sidebar - https://github.com/epicmaxco/vuestic-ui/issues/2028
- UI / Collapses - strange border radii: https://github.com/epicmaxco/vuestic-ui/issues/2021

- [x] Pages / Login/Signup - the "Recover password" link seems to be broken
- [x] Pages / 404 Pages / Advanced layout - Some links are broken
- [x] Pages / Faq - missing prepend slot's padding: https://github.com/epicmaxco/vuestic-ui/issues/2015; Not existing components are substituted with existing.
- [ ] Dashboard -> Bank Details -> Send Details; Lists -> Avatar - fix broken useGlobalConfig

Checklist (visual matching between old and new):
- [x] Dashboard
- [x] Statistics / Charts
- [x] Statistics / Progress Bars
- [x] Forms / Form Elements
- [x] Forms / Medium Editor - Check MediumEditor.vue types afrter 1.4.5 is released!
- [x] Tables / Markup Tables
- [x] UI / Buttons
- [x] UI / Cards
- [x] UI / Chat
- [x] UI / Chips
- [ ] UI / Collapses - Blocked
- [x] UI / Colors
- [x] UI / File Upload
- [x] UI / Grid
- [x] UI / Icons
- [x] UI / Lists
- [x] UI / Modals
- [x] UI / Notifications
- [x] UI / Popovers
- [x] UI / Rating
- [x] UI / Sliders
- [x] UI / Spacing
- [x] UI / Spinners - **HIDDEN**
- [x] UI / Tabs (with changed colors, looks good)
- [x] UI / Timelines - **HIDDEN**
- [x] UI / Tree view
- [x] UI / Typography
- [x] Maps / Google Maps - Changed to MapLibre Maps
- [x] Maps / Yandex Maps
- [x] Maps / Leaflet Maps
- [x] Maps / Bubble Maps
- [x] Maps / Line Maps
- [x] Pages / Login/Signup
- [x] Pages / 404 Pages - All the templates are OK
- [x] Pages / Faq

**Some checked UI pages are still blocked by the broken dropdowns and popovers!**

This issue is currently being edited.
